// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.blokz.grabbit

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object EnginePigeonPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class FormatDto (
  val id: String,
  val ext: String,
  val height: Long? = null,
  val tbr: Long? = null,
  val vcodec: String? = null,
  val acodec: String? = null,
  val audioOnly: Boolean,
  val filesize: Long? = null,
  val label: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FormatDto {
      val id = pigeonVar_list[0] as String
      val ext = pigeonVar_list[1] as String
      val height = pigeonVar_list[2] as Long?
      val tbr = pigeonVar_list[3] as Long?
      val vcodec = pigeonVar_list[4] as String?
      val acodec = pigeonVar_list[5] as String?
      val audioOnly = pigeonVar_list[6] as Boolean
      val filesize = pigeonVar_list[7] as Long?
      val label = pigeonVar_list[8] as String
      return FormatDto(id, ext, height, tbr, vcodec, acodec, audioOnly, filesize, label)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      ext,
      height,
      tbr,
      vcodec,
      acodec,
      audioOnly,
      filesize,
      label,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FormatDto
    return EnginePigeonPigeonUtils.deepEquals(this.id, other.id) && EnginePigeonPigeonUtils.deepEquals(this.ext, other.ext) && EnginePigeonPigeonUtils.deepEquals(this.height, other.height) && EnginePigeonPigeonUtils.deepEquals(this.tbr, other.tbr) && EnginePigeonPigeonUtils.deepEquals(this.vcodec, other.vcodec) && EnginePigeonPigeonUtils.deepEquals(this.acodec, other.acodec) && EnginePigeonPigeonUtils.deepEquals(this.audioOnly, other.audioOnly) && EnginePigeonPigeonUtils.deepEquals(this.filesize, other.filesize) && EnginePigeonPigeonUtils.deepEquals(this.label, other.label)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.id)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.ext)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.height)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.tbr)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.vcodec)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.acodec)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.audioOnly)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.filesize)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.label)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaInfoDto (
  val title: String,
  val id: String? = null,
  val uploader: String? = null,
  val durationSec: Long? = null,
  val thumbnailUrl: String? = null,
  val site: String? = null,
  val description: String? = null,
  val uploadDate: String? = null,
  val formats: List<FormatDto>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaInfoDto {
      val title = pigeonVar_list[0] as String
      val id = pigeonVar_list[1] as String?
      val uploader = pigeonVar_list[2] as String?
      val durationSec = pigeonVar_list[3] as Long?
      val thumbnailUrl = pigeonVar_list[4] as String?
      val site = pigeonVar_list[5] as String?
      val description = pigeonVar_list[6] as String?
      val uploadDate = pigeonVar_list[7] as String?
      val formats = pigeonVar_list[8] as List<FormatDto>
      return MediaInfoDto(title, id, uploader, durationSec, thumbnailUrl, site, description, uploadDate, formats)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      id,
      uploader,
      durationSec,
      thumbnailUrl,
      site,
      description,
      uploadDate,
      formats,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaInfoDto
    return EnginePigeonPigeonUtils.deepEquals(this.title, other.title) && EnginePigeonPigeonUtils.deepEquals(this.id, other.id) && EnginePigeonPigeonUtils.deepEquals(this.uploader, other.uploader) && EnginePigeonPigeonUtils.deepEquals(this.durationSec, other.durationSec) && EnginePigeonPigeonUtils.deepEquals(this.thumbnailUrl, other.thumbnailUrl) && EnginePigeonPigeonUtils.deepEquals(this.site, other.site) && EnginePigeonPigeonUtils.deepEquals(this.description, other.description) && EnginePigeonPigeonUtils.deepEquals(this.uploadDate, other.uploadDate) && EnginePigeonPigeonUtils.deepEquals(this.formats, other.formats)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.title)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.id)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.uploader)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.durationSec)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.thumbnailUrl)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.site)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.description)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.uploadDate)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.formats)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DownloadRequestDto (
  val taskId: String,
  val url: String,
  val formatId: String? = null,
  val audioOnly: Boolean,
  val container: String? = null,
  val subtitleLangs: List<String>? = null,
  val autoSubs: Boolean,
  val subtitleFormat: String? = null,
  val embedThumbnail: Boolean,
  val embedMetadata: Boolean,
  val outputDir: String,
  val filenameTemplate: String,
  val rateLimit: String? = null,
  val concurrentFragments: Long? = null,
  val audioQuality: String? = null,
  val downloadArchivePath: String? = null,
  val extraArgs: List<String>? = null,
  val sponsorBlock: String? = null,
  val sponsorBlockCategories: List<String>? = null,
  val embedChapters: Boolean,
  val splitChapters: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadRequestDto {
      val taskId = pigeonVar_list[0] as String
      val url = pigeonVar_list[1] as String
      val formatId = pigeonVar_list[2] as String?
      val audioOnly = pigeonVar_list[3] as Boolean
      val container = pigeonVar_list[4] as String?
      val subtitleLangs = pigeonVar_list[5] as List<String>?
      val autoSubs = pigeonVar_list[6] as Boolean
      val subtitleFormat = pigeonVar_list[7] as String?
      val embedThumbnail = pigeonVar_list[8] as Boolean
      val embedMetadata = pigeonVar_list[9] as Boolean
      val outputDir = pigeonVar_list[10] as String
      val filenameTemplate = pigeonVar_list[11] as String
      val rateLimit = pigeonVar_list[12] as String?
      val concurrentFragments = pigeonVar_list[13] as Long?
      val audioQuality = pigeonVar_list[14] as String?
      val downloadArchivePath = pigeonVar_list[15] as String?
      val extraArgs = pigeonVar_list[16] as List<String>?
      val sponsorBlock = pigeonVar_list[17] as String?
      val sponsorBlockCategories = pigeonVar_list[18] as List<String>?
      val embedChapters = pigeonVar_list[19] as Boolean
      val splitChapters = pigeonVar_list[20] as Boolean
      return DownloadRequestDto(taskId, url, formatId, audioOnly, container, subtitleLangs, autoSubs, subtitleFormat, embedThumbnail, embedMetadata, outputDir, filenameTemplate, rateLimit, concurrentFragments, audioQuality, downloadArchivePath, extraArgs, sponsorBlock, sponsorBlockCategories, embedChapters, splitChapters)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      taskId,
      url,
      formatId,
      audioOnly,
      container,
      subtitleLangs,
      autoSubs,
      subtitleFormat,
      embedThumbnail,
      embedMetadata,
      outputDir,
      filenameTemplate,
      rateLimit,
      concurrentFragments,
      audioQuality,
      downloadArchivePath,
      extraArgs,
      sponsorBlock,
      sponsorBlockCategories,
      embedChapters,
      splitChapters,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DownloadRequestDto
    return EnginePigeonPigeonUtils.deepEquals(this.taskId, other.taskId) && EnginePigeonPigeonUtils.deepEquals(this.url, other.url) && EnginePigeonPigeonUtils.deepEquals(this.formatId, other.formatId) && EnginePigeonPigeonUtils.deepEquals(this.audioOnly, other.audioOnly) && EnginePigeonPigeonUtils.deepEquals(this.container, other.container) && EnginePigeonPigeonUtils.deepEquals(this.subtitleLangs, other.subtitleLangs) && EnginePigeonPigeonUtils.deepEquals(this.autoSubs, other.autoSubs) && EnginePigeonPigeonUtils.deepEquals(this.subtitleFormat, other.subtitleFormat) && EnginePigeonPigeonUtils.deepEquals(this.embedThumbnail, other.embedThumbnail) && EnginePigeonPigeonUtils.deepEquals(this.embedMetadata, other.embedMetadata) && EnginePigeonPigeonUtils.deepEquals(this.outputDir, other.outputDir) && EnginePigeonPigeonUtils.deepEquals(this.filenameTemplate, other.filenameTemplate) && EnginePigeonPigeonUtils.deepEquals(this.rateLimit, other.rateLimit) && EnginePigeonPigeonUtils.deepEquals(this.concurrentFragments, other.concurrentFragments) && EnginePigeonPigeonUtils.deepEquals(this.audioQuality, other.audioQuality) && EnginePigeonPigeonUtils.deepEquals(this.downloadArchivePath, other.downloadArchivePath) && EnginePigeonPigeonUtils.deepEquals(this.extraArgs, other.extraArgs) && EnginePigeonPigeonUtils.deepEquals(this.sponsorBlock, other.sponsorBlock) && EnginePigeonPigeonUtils.deepEquals(this.sponsorBlockCategories, other.sponsorBlockCategories) && EnginePigeonPigeonUtils.deepEquals(this.embedChapters, other.embedChapters) && EnginePigeonPigeonUtils.deepEquals(this.splitChapters, other.splitChapters)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.taskId)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.url)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.formatId)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.audioOnly)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.container)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.subtitleLangs)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.autoSubs)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.subtitleFormat)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.embedThumbnail)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.embedMetadata)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.outputDir)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.filenameTemplate)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.rateLimit)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.concurrentFragments)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.audioQuality)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.downloadArchivePath)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.extraArgs)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.sponsorBlock)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.sponsorBlockCategories)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.embedChapters)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.splitChapters)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProgressDto (
  val taskId: String,
  val percent: Double,
  val speedBps: Double,
  val etaSec: Long? = null,
  val stage: String,
  val error: String? = null,
  val line: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProgressDto {
      val taskId = pigeonVar_list[0] as String
      val percent = pigeonVar_list[1] as Double
      val speedBps = pigeonVar_list[2] as Double
      val etaSec = pigeonVar_list[3] as Long?
      val stage = pigeonVar_list[4] as String
      val error = pigeonVar_list[5] as String?
      val line = pigeonVar_list[6] as String?
      return ProgressDto(taskId, percent, speedBps, etaSec, stage, error, line)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      taskId,
      percent,
      speedBps,
      etaSec,
      stage,
      error,
      line,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProgressDto
    return EnginePigeonPigeonUtils.deepEquals(this.taskId, other.taskId) && EnginePigeonPigeonUtils.deepEquals(this.percent, other.percent) && EnginePigeonPigeonUtils.deepEquals(this.speedBps, other.speedBps) && EnginePigeonPigeonUtils.deepEquals(this.etaSec, other.etaSec) && EnginePigeonPigeonUtils.deepEquals(this.stage, other.stage) && EnginePigeonPigeonUtils.deepEquals(this.error, other.error) && EnginePigeonPigeonUtils.deepEquals(this.line, other.line)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.taskId)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.percent)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.speedBps)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.etaSec)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.stage)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.error)
    result = 31 * result + EnginePigeonPigeonUtils.deepHash(this.line)
    return result
  }
}
private open class EnginePigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FormatDto.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaInfoDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadRequestDto.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProgressDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is FormatDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is MediaInfoDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is DownloadRequestDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ProgressDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface YtDlpHostApi {
  fun probe(url: String, callback: (Result<MediaInfoDto>) -> Unit)
  /**
   * Raw `yt-dlp --flat-playlist -J <url>` stdout (parsed in Dart). Returns a
   * single-video JSON when the URL isn't a playlist/carousel.
   */
  fun expandRaw(url: String, callback: (Result<String>) -> Unit)
  fun startDownload(request: DownloadRequestDto)
  fun cancel(taskId: String)
  fun engineVersions(callback: (Result<String>) -> Unit)
  fun updateEngine(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by YtDlpHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      EnginePigeonPigeonCodec()
    }
    /** Sets up an instance of `YtDlpHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: YtDlpHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grabbit.YtDlpHostApi.probe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.probe(urlArg) { result: Result<MediaInfoDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(EnginePigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grabbit.YtDlpHostApi.expandRaw$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.expandRaw(urlArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(EnginePigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grabbit.YtDlpHostApi.startDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as DownloadRequestDto
            val wrapped: List<Any?> = try {
              api.startDownload(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              EnginePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grabbit.YtDlpHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancel(taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              EnginePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grabbit.YtDlpHostApi.engineVersions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.engineVersions{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(EnginePigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grabbit.YtDlpHostApi.updateEngine$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.updateEngine{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(EnginePigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class YtDlpFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by YtDlpFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      EnginePigeonPigeonCodec()
    }
  }
  fun onProgress(progressArg: ProgressDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.grabbit.YtDlpFlutterApi.onProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(EnginePigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/**
 * Foreground-service control + connectivity probe for the download queue.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ServiceHostApi {
  fun startService(text: String, progress: Long, indeterminate: Boolean)
  fun updateNotification(text: String, progress: Long, indeterminate: Boolean)
  fun stopService()
  fun isUnmetered(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by ServiceHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      EnginePigeonPigeonCodec()
    }
    /** Sets up an instance of `ServiceHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ServiceHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grabbit.ServiceHostApi.startService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            val progressArg = args[1] as Long
            val indeterminateArg = args[2] as Boolean
            val wrapped: List<Any?> = try {
              api.startService(textArg, progressArg, indeterminateArg)
              listOf(null)
            } catch (exception: Throwable) {
              EnginePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grabbit.ServiceHostApi.updateNotification$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            val progressArg = args[1] as Long
            val indeterminateArg = args[2] as Boolean
            val wrapped: List<Any?> = try {
              api.updateNotification(textArg, progressArg, indeterminateArg)
              listOf(null)
            } catch (exception: Throwable) {
              EnginePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grabbit.ServiceHostApi.stopService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopService()
              listOf(null)
            } catch (exception: Throwable) {
              EnginePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grabbit.ServiceHostApi.isUnmetered$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isUnmetered{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(EnginePigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class ServiceFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ServiceFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      EnginePigeonPigeonCodec()
    }
  }
  /** The notification's "Stop" action was tapped. */
  fun onStopRequested(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.grabbit.ServiceFlutterApi.onStopRequested$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(EnginePigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/**
 * Delivers text/URLs shared into the app via the Android share sheet
 * (`ACTION_SEND` / `ACTION_SEND_MULTIPLE`). See docs/design/P8-PLAN.md (P8a).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ShareHostApi {
  /**
   * The shared text the app was cold-launched with, consumed once (cleared on
   * read). Null when the launch wasn't a share.
   */
  fun takeInitialSharedText(): String?

  companion object {
    /** The codec used by ShareHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      EnginePigeonPigeonCodec()
    }
    /** Sets up an instance of `ShareHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ShareHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grabbit.ShareHostApi.takeInitialSharedText$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.takeInitialSharedText())
            } catch (exception: Throwable) {
              EnginePigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class ShareFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ShareFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      EnginePigeonPigeonCodec()
    }
  }
  /** A share arrived while the app was already running (`onNewIntent`). */
  fun onSharedText(textArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.grabbit.ShareFlutterApi.onSharedText$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(textArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(EnginePigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/**
 * Export a private library file to the device. [type] is video|audio|image.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface StorageHostApi {
  /** Launches the SAF folder picker; returns the persisted tree URI or null. */
  fun pickExportFolder(callback: (Result<String?>) -> Unit)
  /** Copies the file into a user-picked SAF tree; returns the saved doc URI. */
  fun exportToTree(filePath: String, treeUri: String, type: String, subdir: String?, callback: (Result<String>) -> Unit)
  /** Copies the file into the public MediaStore (gallery-visible, API 29+). */
  fun exportToMediaStore(filePath: String, type: String, subdir: String?, callback: (Result<String>) -> Unit)

  companion object {
    /** The codec used by StorageHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      EnginePigeonPigeonCodec()
    }
    /** Sets up an instance of `StorageHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: StorageHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grabbit.StorageHostApi.pickExportFolder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.pickExportFolder{ result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(EnginePigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grabbit.StorageHostApi.exportToTree$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            val treeUriArg = args[1] as String
            val typeArg = args[2] as String
            val subdirArg = args[3] as String?
            api.exportToTree(filePathArg, treeUriArg, typeArg, subdirArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(EnginePigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grabbit.StorageHostApi.exportToMediaStore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            val typeArg = args[1] as String
            val subdirArg = args[2] as String?
            api.exportToMediaStore(filePathArg, typeArg, subdirArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(EnginePigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
