// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class FormatDto {
  FormatDto({
    required this.id,
    required this.ext,
    this.height,
    this.tbr,
    this.vcodec,
    this.acodec,
    required this.audioOnly,
    this.filesize,
    required this.label,
  });

  String id;

  String ext;

  int? height;

  int? tbr;

  String? vcodec;

  String? acodec;

  bool audioOnly;

  int? filesize;

  String label;

  List<Object?> _toList() {
    return <Object?>[
      id,
      ext,
      height,
      tbr,
      vcodec,
      acodec,
      audioOnly,
      filesize,
      label,
    ];
  }

  Object encode() {
    return _toList();
  }

  static FormatDto decode(Object result) {
    result as List<Object?>;
    return FormatDto(
      id: result[0]! as String,
      ext: result[1]! as String,
      height: result[2] as int?,
      tbr: result[3] as int?,
      vcodec: result[4] as String?,
      acodec: result[5] as String?,
      audioOnly: result[6]! as bool,
      filesize: result[7] as int?,
      label: result[8]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FormatDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(ext, other.ext) &&
        _deepEquals(height, other.height) &&
        _deepEquals(tbr, other.tbr) &&
        _deepEquals(vcodec, other.vcodec) &&
        _deepEquals(acodec, other.acodec) &&
        _deepEquals(audioOnly, other.audioOnly) &&
        _deepEquals(filesize, other.filesize) &&
        _deepEquals(label, other.label);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class MediaInfoDto {
  MediaInfoDto({
    required this.title,
    this.id,
    this.uploader,
    this.durationSec,
    this.thumbnailUrl,
    this.site,
    this.description,
    this.uploadDate,
    required this.formats,
  });

  String title;

  String? id;

  String? uploader;

  int? durationSec;

  String? thumbnailUrl;

  String? site;

  String? description;

  String? uploadDate;

  List<FormatDto> formats;

  List<Object?> _toList() {
    return <Object?>[
      title,
      id,
      uploader,
      durationSec,
      thumbnailUrl,
      site,
      description,
      uploadDate,
      formats,
    ];
  }

  Object encode() {
    return _toList();
  }

  static MediaInfoDto decode(Object result) {
    result as List<Object?>;
    return MediaInfoDto(
      title: result[0]! as String,
      id: result[1] as String?,
      uploader: result[2] as String?,
      durationSec: result[3] as int?,
      thumbnailUrl: result[4] as String?,
      site: result[5] as String?,
      description: result[6] as String?,
      uploadDate: result[7] as String?,
      formats: (result[8]! as List<Object?>).cast<FormatDto>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaInfoDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) &&
        _deepEquals(id, other.id) &&
        _deepEquals(uploader, other.uploader) &&
        _deepEquals(durationSec, other.durationSec) &&
        _deepEquals(thumbnailUrl, other.thumbnailUrl) &&
        _deepEquals(site, other.site) &&
        _deepEquals(description, other.description) &&
        _deepEquals(uploadDate, other.uploadDate) &&
        _deepEquals(formats, other.formats);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class DownloadRequestDto {
  DownloadRequestDto({
    required this.taskId,
    required this.url,
    this.formatId,
    required this.audioOnly,
    this.container,
    this.subtitleLangs,
    required this.autoSubs,
    this.subtitleFormat,
    required this.embedThumbnail,
    required this.embedMetadata,
    required this.outputDir,
    required this.filenameTemplate,
    this.rateLimit,
    this.concurrentFragments,
    this.audioQuality,
    this.downloadArchivePath,
    this.extraArgs,
    this.sponsorBlock,
    this.sponsorBlockCategories,
    required this.embedChapters,
    required this.splitChapters,
  });

  String taskId;

  String url;

  String? formatId;

  bool audioOnly;

  String? container;

  List<String>? subtitleLangs;

  bool autoSubs;

  String? subtitleFormat;

  bool embedThumbnail;

  bool embedMetadata;

  String outputDir;

  String filenameTemplate;

  String? rateLimit;

  int? concurrentFragments;

  String? audioQuality;

  String? downloadArchivePath;

  List<String>? extraArgs;

  String? sponsorBlock;

  List<String>? sponsorBlockCategories;

  bool embedChapters;

  bool splitChapters;

  List<Object?> _toList() {
    return <Object?>[
      taskId,
      url,
      formatId,
      audioOnly,
      container,
      subtitleLangs,
      autoSubs,
      subtitleFormat,
      embedThumbnail,
      embedMetadata,
      outputDir,
      filenameTemplate,
      rateLimit,
      concurrentFragments,
      audioQuality,
      downloadArchivePath,
      extraArgs,
      sponsorBlock,
      sponsorBlockCategories,
      embedChapters,
      splitChapters,
    ];
  }

  Object encode() {
    return _toList();
  }

  static DownloadRequestDto decode(Object result) {
    result as List<Object?>;
    return DownloadRequestDto(
      taskId: result[0]! as String,
      url: result[1]! as String,
      formatId: result[2] as String?,
      audioOnly: result[3]! as bool,
      container: result[4] as String?,
      subtitleLangs: (result[5] as List<Object?>?)?.cast<String>(),
      autoSubs: result[6]! as bool,
      subtitleFormat: result[7] as String?,
      embedThumbnail: result[8]! as bool,
      embedMetadata: result[9]! as bool,
      outputDir: result[10]! as String,
      filenameTemplate: result[11]! as String,
      rateLimit: result[12] as String?,
      concurrentFragments: result[13] as int?,
      audioQuality: result[14] as String?,
      downloadArchivePath: result[15] as String?,
      extraArgs: (result[16] as List<Object?>?)?.cast<String>(),
      sponsorBlock: result[17] as String?,
      sponsorBlockCategories: (result[18] as List<Object?>?)?.cast<String>(),
      embedChapters: result[19]! as bool,
      splitChapters: result[20]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DownloadRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(taskId, other.taskId) &&
        _deepEquals(url, other.url) &&
        _deepEquals(formatId, other.formatId) &&
        _deepEquals(audioOnly, other.audioOnly) &&
        _deepEquals(container, other.container) &&
        _deepEquals(subtitleLangs, other.subtitleLangs) &&
        _deepEquals(autoSubs, other.autoSubs) &&
        _deepEquals(subtitleFormat, other.subtitleFormat) &&
        _deepEquals(embedThumbnail, other.embedThumbnail) &&
        _deepEquals(embedMetadata, other.embedMetadata) &&
        _deepEquals(outputDir, other.outputDir) &&
        _deepEquals(filenameTemplate, other.filenameTemplate) &&
        _deepEquals(rateLimit, other.rateLimit) &&
        _deepEquals(concurrentFragments, other.concurrentFragments) &&
        _deepEquals(audioQuality, other.audioQuality) &&
        _deepEquals(downloadArchivePath, other.downloadArchivePath) &&
        _deepEquals(extraArgs, other.extraArgs) &&
        _deepEquals(sponsorBlock, other.sponsorBlock) &&
        _deepEquals(sponsorBlockCategories, other.sponsorBlockCategories) &&
        _deepEquals(embedChapters, other.embedChapters) &&
        _deepEquals(splitChapters, other.splitChapters);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class ProgressDto {
  ProgressDto({
    required this.taskId,
    required this.percent,
    required this.speedBps,
    this.etaSec,
    required this.stage,
    this.error,
    this.line,
  });

  String taskId;

  double percent;

  double speedBps;

  int? etaSec;

  String stage;

  String? error;

  String? line;

  List<Object?> _toList() {
    return <Object?>[taskId, percent, speedBps, etaSec, stage, error, line];
  }

  Object encode() {
    return _toList();
  }

  static ProgressDto decode(Object result) {
    result as List<Object?>;
    return ProgressDto(
      taskId: result[0]! as String,
      percent: result[1]! as double,
      speedBps: result[2]! as double,
      etaSec: result[3] as int?,
      stage: result[4]! as String,
      error: result[5] as String?,
      line: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProgressDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(taskId, other.taskId) &&
        _deepEquals(percent, other.percent) &&
        _deepEquals(speedBps, other.speedBps) &&
        _deepEquals(etaSec, other.etaSec) &&
        _deepEquals(stage, other.stage) &&
        _deepEquals(error, other.error) &&
        _deepEquals(line, other.line);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is FormatDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is MediaInfoDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is DownloadRequestDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is ProgressDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return FormatDto.decode(readValue(buffer)!);
      case 130:
        return MediaInfoDto.decode(readValue(buffer)!);
      case 131:
        return DownloadRequestDto.decode(readValue(buffer)!);
      case 132:
        return ProgressDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class YtDlpHostApi {
  /// Constructor for [YtDlpHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  YtDlpHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<MediaInfoDto> probe(String url) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.grabbit.YtDlpHostApi.probe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[url],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as MediaInfoDto;
  }

  /// Raw `yt-dlp --flat-playlist -J <url>` stdout (parsed in Dart). Returns a
  /// single-video JSON when the URL isn't a playlist/carousel.
  Future<String> expandRaw(String url) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.grabbit.YtDlpHostApi.expandRaw$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[url],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<void> startDownload(DownloadRequestDto request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.grabbit.YtDlpHostApi.startDownload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancel(String taskId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.grabbit.YtDlpHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[taskId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String> engineVersions() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.grabbit.YtDlpHostApi.engineVersions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<void> updateEngine() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.grabbit.YtDlpHostApi.updateEngine$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class YtDlpFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onProgress(ProgressDto progress);

  static void setUp(
    YtDlpFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.grabbit.YtDlpFlutterApi.onProgress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ProgressDto arg_progress = args[0]! as ProgressDto;
          try {
            api.onProgress(arg_progress);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}

/// Foreground-service control + connectivity probe for the download queue.
class ServiceHostApi {
  /// Constructor for [ServiceHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ServiceHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> startService(
    String text,
    int progress,
    bool indeterminate,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.grabbit.ServiceHostApi.startService$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[text, progress, indeterminate],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> updateNotification(
    String text,
    int progress,
    bool indeterminate,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.grabbit.ServiceHostApi.updateNotification$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[text, progress, indeterminate],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stopService() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.grabbit.ServiceHostApi.stopService$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> isUnmetered() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.grabbit.ServiceHostApi.isUnmetered$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}

abstract class ServiceFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// The notification's "Stop" action was tapped.
  void onStopRequested();

  static void setUp(
    ServiceFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.grabbit.ServiceFlutterApi.onStopRequested$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onStopRequested();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}

/// Delivers text/URLs shared into the app via the Android share sheet
/// (`ACTION_SEND` / `ACTION_SEND_MULTIPLE`). See docs/design/P8-PLAN.md (P8a).
class ShareHostApi {
  /// Constructor for [ShareHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ShareHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// The shared text the app was cold-launched with, consumed once (cleared on
  /// read). Null when the launch wasn't a share.
  Future<String?> takeInitialSharedText() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.grabbit.ShareHostApi.takeInitialSharedText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }
}

abstract class ShareFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// A share arrived while the app was already running (`onNewIntent`).
  void onSharedText(String text);

  static void setUp(
    ShareFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.grabbit.ShareFlutterApi.onSharedText$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_text = args[0]! as String;
          try {
            api.onSharedText(arg_text);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}

/// Export a private library file to the device. [type] is video|audio|image.
class StorageHostApi {
  /// Constructor for [StorageHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  StorageHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Launches the SAF folder picker; returns the persisted tree URI or null.
  Future<String?> pickExportFolder() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.grabbit.StorageHostApi.pickExportFolder$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  /// Copies the file into a user-picked SAF tree; returns the saved doc URI.
  Future<String> exportToTree(
    String filePath,
    String treeUri,
    String type,
    String? subdir,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.grabbit.StorageHostApi.exportToTree$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[filePath, treeUri, type, subdir],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  /// Copies the file into the public MediaStore (gallery-visible, API 29+).
  Future<String> exportToMediaStore(
    String filePath,
    String type,
    String? subdir,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.grabbit.StorageHostApi.exportToMediaStore$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[filePath, type, subdir],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }
}
